-- @block
CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY , 
    name VARCHAR(100) NOT NULL , 
    email VARCHAR(100) NOT NULL , 
    rule ENUM('ADMIN' , 'STUDENT' , 'COACH') NOT NULL , 
    created_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP
)